import mockjs from "mockjs";

mockjs.mock('/api/api', 'get', {
    status: true,
    data: [
        {
            key: '1',
            num: '1',
            taskCode: '202208100001',
            unitCode: '0100058',
            workType: '补货工单',
            workMode: '手动',
            taskStatus: '待办',
            person: '1234',
            createDate: '2022.08.10 09:33.12',
            // operate:''
        },
        {
            key: '2',
            num: '2',
            taskCode: '202208100001',
            unitCode: '0100058',
            workType: '补货工单',
            workMode: '手动',
            taskStatus: '待办',
            person: '1234',
            createDate: '2022.08.10 09:33.12',
            // operate:''
        },
        {
            key: '3',
            num: '3',
            taskCode: '202208100001',
            unitCode: '0100058',
            workType: '补货工单',
            workMode: '手动',
            taskStatus: '待办',
            person: '1234',
            createDate: '2022.08.10 09:33.12',
            // operate:''
        },
        {
            key: '4',
            num: '4',
            taskCode: '202208100001',
            unitCode: '0100058',
            workType: '补货工单',
            workMode: '手动',
            taskStatus: '待办',
            person: '1234',
            createDate: '2022.08.10 09:33.12',
            // operate:''
        },
        {
            key: '5',
            num: '5',
            taskCode: '202208100001',
            unitCode: '0100058',
            workType: '补货工单',
            workMode: '手动',
            taskStatus: '待办',
            person: '1234',
            createDate: '2022.08.10 09:33.12',
            // operate:''
        },
        {
            key: '6',
            num: '6',
            taskCode: '202208100001',
            unitCode: '0100058',
            workType: '补货工单',
            workMode: '手动',
            taskStatus: '待办',
            person: '1234',
            createDate: '2022.08.10 09:33.12',
            // operate:''
        },
        {
            key: '7',
            num: '7',
            taskCode: '202208100001',
            unitCode: '0100058',
            workType: '补货工单',
            workMode: '手动',
            taskStatus: '待办',
            person: '1234',
            createDate: '2022.08.10 09:33.12',
            // operate:''
        },
        {
            key: '8',
            num: '8',
            taskCode: '202208100001',
            unitCode: '0100058',
            workType: '补货工单',
            workMode: '手动',
            taskStatus: '待办',
            person: '1234',
            createDate: '2022.08.10 09:33.12',
            // operate:''
        },
        {
            key: '9',
            num: '9',
            taskCode: '202208100001',
            unitCode: '0100058',
            workType: '补货工单',
            workMode: '手动',
            taskStatus: '待办',
            person: '1234',
            createDate: '2022.08.10 09:33.12',
            // operate:''
        },
        {
            key: '10',
            num: '10',
            taskCode: '202208100001',
            unitCode: '0100058',
            workType: '补货工单',
            workMode: '手动',
            taskStatus: '待办',
            person: '1234',
            createDate: '2022.08.10 09:33.12',
            // operate:''
        },
        {
            key: '11',
            num: '11',
            taskCode: '202208100001',
            unitCode: '0100058',
            workType: '补货工单',
            workMode: '手动',
            taskStatus: '待办',
            person: '1234',
            createDate: '2022.08.10 09:33.12',
            // operate:''
        },

    ]
})
mockjs.mock('/api/api1', 'get', {
    status: true,
    data: [
        {
            key: '1',
            num: '1',
            ordernum: '0100000254313656563942651',
            name: '泡面1',
            money: '4.50',
            unitCode: '01000002',
            ordertype: '出货成功',
            date: '2022.08.11 04:00:11',
        },
        {
            key: '2',
            num: '2',
            ordernum: '0100000254313656563942651',
            name: '泡面1',
            money: '4.50',
            unitCode: '01000002',
            ordertype: '出货成功',
            date: '2022.08.11 04:00:11',
        },
        {
            key: '3',
            num: '3',
            ordernum: '0100000254313656563942651',
            name: '泡面1',
            money: '4.50',
            unitCode: '01000002',
            ordertype: '出货成功',
            date: '2022.08.11 04:00:11',
        },
        {
            key: '4',
            num: '4',
            ordernum: '0100000254313656563942651',
            name: '泡面1',
            money: '4.50',
            unitCode: '01000002',
            ordertype: '出货成功',
            date: '2022.08.11 04:00:11',
        },
        {
            key: '5',
            num: '5',
            ordernum: '0100000254313656563942651',
            name: '泡面1',
            money: '4.50',
            unitCode: '01000002',
            ordertype: '出货成功',
            date: '2022.08.11 04:00:11',
        },
        {
            key: '6',
            num: '6',
            ordernum: '0100000254313656563942651',
            name: '泡面1',
            money: '4.50',
            unitCode: '01000002',
            ordertype: '出货成功',
            date: '2022.08.11 04:00:11',
        },
        {
            key: '7',
            num: '7',
            ordernum: '0100000254313656563942651',
            name: '泡面1',
            money: '4.50',
            unitCode: '01000002',
            ordertype: '出货成功',
            date: '2022.08.11 04:00:11',
        },
        {
            key: '8',
            num: '8',
            ordernum: '0100000254313656563942651',
            name: '泡面1',
            money: '4.50',
            unitCode: '01000002',
            ordertype: '出货成功',
            date: '2022.08.11 04:00:11',
        },
        {
            key: '9',
            num: '9',
            ordernum: '0100000254313656563942651',
            name: '泡面1',
            money: '4.50',
            unitCode: '01000002',
            ordertype: '出货成功',
            date: '2022.08.11 04:00:11',
        },
    ]
})
mockjs.mock('/api/api2', 'get', {
    status: true,
    data: [
        {
            key: '1',
            num: '1',
            names: 'Revic',
            area: '十一区',
            job: '维修者',
            phone: '13252543345',
        },
        {
            key: '2',
            num: '2',
            names: 'JOJO',
            area: '十一区',
            job: '维修者',
            phone: '13252543345',
        },
        {
            key: '3',
            num: '3',
            names: 'W',
            area: '十一区',
            job: '维修者',
            phone: '13252543345',
        },
        {
            key: '4',
            num: '4',
            names: 'Revic',
            area: '十一区',
            job: '维修者',
            phone: '13252543345',
        },
        {
            key: '5',
            num: '5',
            names: 'Revic',
            area: '十一区',
            job: '运营者',
            phone: '13252543345',
        },
        {
            key: '6',
            num: '6',
            names: 'Revic',
            area: '十一区',
            job: '运营者',
            phone: '13252543345',
        },
        {
            key: '7',
            num: '7',
            names: 'Revic',
            area: '十一区',
            job: '运营者',
            phone: '13252543345',
        },
        {
            key: '8',
            num: '8',
            names: 'Revic',
            area: '十一区',
            job: '运营者',
            phone: '13252543345',
        },
    ]
})
mockjs.mock('/api/api3', 'get', {
    status: true,
    data: [
        {
            key: '1',
            num: '1',
            names: '可口可乐',
            img: '',
            brand: '可口可乐',
            specifications: '550ml',
            price: '5.00',
            type: '',
        },
        {
            key: '2',
            num: '2',
            names: '可口可乐',
            img: '',
            brand: '可口可乐',
            specifications: '550ml',
            price: '5.00',
            type: '',
        },
        {
            key: '3',
            num: '3',
            names: '冰红茶',
            img: '',
            brand: '康师傅',
            specifications: '550ml',
            price: '5.00',
            type: '',
        },
        {
            key: '4',
            num: '4',
            names: '冰红茶',
            img: '',
            brand: '康师傅',
            specifications: '550ml',
            price: '5.00',
            type: '',
        },
        {
            key: '5',
            num: '5',
            names: '矿泉水',
            img: '',
            brand: '怡宝',
            specifications: '550ml',
            price: '5.00',
            type: '',
        },
        {
            key: '6',
            num: '6',
            names: '矿泉水',
            img: '',
            brand: '怡宝',
            specifications: '550ml',
            price: '5.00',
            type: '',
        },
        {
            key: '7',
            num: '7',
            names: '可口可乐',
            img: '',
            brand: '可口可乐',
            specifications: '550ml',
            price: '5.00',
            type: '',
        },
        {
            key: '8',
            num: '8',
            names: '可口可乐',
            img: '',
            brand: '可口可乐',
            specifications: '550ml',
            price: '5.00',
            type: '',
        },
    ]
})
mockjs.mock('/api/api4', 'get', {
    status: true,
    data: [
        {
            key: '1',
            num: '1',
            names: 'Revic',
            area: '十一区',
            job: '维修者',
            phone: '13252543345',
            finish: '0',
            ing: '0',
            reject:'0',
        },
        {
            key: '2',
            num: '2',
            names: 'JOJO',
            area: '十一区',
            job: '维修者',
            phone: '13252543345',
            finish: '0',
            ing: '0',
            reject:'0',
        },
        {
            key: '3',
            num: '3',
            names: 'W',
            area: '十一区',
            job: '维修者',
            phone: '13252543345',
            finish: '0',
            ing: '0',
            reject:'0',
        },
        {
            key: '4',
            num: '4',
            names: 'Revic',
            area: '十一区',
            job: '维修者',
            phone: '13252543345',
            finish: '0',
            ing: '0',
            reject:'0',
        },
        {
            key: '5',
            num: '5',
            names: 'Revic',
            area: '十一区',
            job: '运营者',
            phone: '13252543345',
            finish: '0',
            ing: '0',
            reject:'0',
        },
        {
            key: '6',
            num: '6',
            names: 'Revic',
            area: '十一区',
            job: '运营者',
            phone: '13252543345',
            finish: '0',
            ing: '0',
            reject:'0',
        },
        {
            key: '7',
            num: '7',
            names: 'Revic',
            area: '十一区',
            job: '运营者',
            phone: '13252543345',
            finish: '0',
            ing: '0',
            reject:'0',
        },
        {
            key: '8',
            num: '8',
            names: 'Revic',
            area: '十一区',
            job: '运营者',
            phone: '13252543345',
            finish: '0',
            ing: '0',
            reject:'0',
        },
    ]
})
mockjs.mock('/api/api5', 'get', {          //region
    status: true,
    data: [
        {
            key: '1',
            num: '1',
            areanames: '霍营街道',
            bit: '3',
            Remarks: '霍营街道',
        },
        {
            key: '2',
            num: '2',
            areanames: '城北街道',
            bit: '3',
            Remarks: '城北街道',
        },
        {
            key: '3',
            num: '3',
            areanames: '西直门街道',
            bit: '3',
            Remarks: '西直门街道',
        },
        {
            key: '4',
            num: '4',
            areanames: '金燕龙办公楼',
            bit: '3',
            Remarks: '金燕龙办公楼',
        },
        {
            key: '5',
            num: '5',
            areanames: '北京1街道',
            bit: '3',
            Remarks: '北京1街道',
        },
        {
            key: '6',
            num: '6',
            areanames: '北京5街道',
            bit: '3',
            Remarks: '北京5街道',
        },
        {
            key: '7',
            num: '7',
            areanames: '北京6街道',
            bit: '3',
            Remarks: '北京6街道',
        },
    ]
})
mockjs.mock('/api/api6', 'get', {          //node
    status: true,
    data: [
        {
            key: '1',
            num: '1',
            pointnames: '北京广场',
            area: '北京1街道',
            business: '学校',
            partners:'天华物业',
            address:'北京广场1层'
        },
        {
            key: '2',
            num: '2',
            pointnames: '北京广场',
            area: '北京2街道',
            business: '学校',
            partners:'天华物业',
            address:'北京广场1层'
        },
        {
            key: '3',
            num: '3',
            pointnames: '北京广场',
            area: '北京2街道',
            business: '学校',
            partners:'天华物业',
            address:'北京广场1层'
        },
        {
            key: '4',
            num: '4',
            pointnames: '北京广场',
            area: '北京4街道',
            business: '学校',
            partners:'天华物业',
            address:'北京广场1层'
        },
        {
            key: '5',
            num: '5',
            pointnames: '北京广场',
            area: '北京1街道',
            business: '学校',
            partners:'天华物业',
            address:'北京广场1层'
        },
        {
            key: '6',
            num: '6',
            pointnames: '北京广场',
            area: '北京1街道',
            business: '学校',
            partners:'天华物业',
            address:'北京广场1层'
        },
        {
            key: '7',
            num: '7',
            pointnames: '北京广场',
            area: '北京1街道',
            business: '学校',
            partners:'天华物业',
            address:'北京广场1层'
        },
    ]
})
mockjs.mock('/api/api7', 'get', {          //partner
    status: true,
    data: [
        {
            key: '1',
            num: '1',
            partner: '天华物业',
            account: '13800000',
            quantity: '99',
            Divide:'88',
            contacts:'JOJO',
            phone:'17766233007',
        },
        {
            key: '2',
            num: '2',
            partner: '天华物业',
            account: '13800000',
            quantity: '99',
            Divide:'88',
            contacts:'JOJO',
            phone:'17766233007',
        },
        {
            key: '3',
            num: '3',
            partner: '天华物业',
            account: '13800000',
            quantity: '99',
            Divide:'88',
            contacts:'JOJO',
            phone:'17766233007',
        },
    ]
})